import type {
  Citation,
  Competitor,
  EngineVisibility,
  Metric,
  MissingSource,
  Recommendation,
  Report,
  TrackedQuery,
  VisibilityBreakdown,
} from "./types";

const history = (values: number[]): { label: string; value: number }[] =>
  values.map((value, i) => ({ label: `W${i + 1}`, value }));

export const mockMetrics: Metric[] = [
  {
    key: "visibility",
    label: "AI Visibility",
    value: 72,
    unit: "score",
    change: 4.2,
    history: history([58, 61, 63, 62, 66, 69, 72]),
  },
  {
    key: "mention",
    label: "Mention Rate",
    value: 68,
    unit: "percent",
    change: 3.1,
    history: history([54, 57, 59, 61, 63, 66, 68]),
  },
  {
    key: "recommendation",
    label: "Recommendation Rate",
    value: 61,
    unit: "percent",
    change: -1.4,
    history: history([59, 62, 64, 63, 63, 62, 61]),
  },
  {
    key: "citation",
    label: "Citation Coverage",
    value: 54,
    unit: "percent",
    change: 2.6,
    history: history([44, 46, 48, 49, 51, 52, 54]),
  },
];

export const mockEngines: EngineVisibility[] = [
  { engine: "ChatGPT", visibility: 76, responses: 412 },
  { engine: "Gemini", visibility: 71, responses: 338 },
  { engine: "Claude", visibility: 68, responses: 291 },
  { engine: "Other AI Search", visibility: 59, responses: 164 },
];

export const mockBreakdown: VisibilityBreakdown[] = [
  { label: "Mention Rate", value: 68, description: "Tracked responses that mention your brand." },
  {
    label: "Recommendation Rate",
    value: 61,
    description: "Responses where your brand is recommended.",
  },
  { label: "Query Coverage", value: 74, description: "Tracked queries with any observed presence." },
  { label: "Citation Coverage", value: 54, description: "Responses citing sources about you." },
  { label: "Brand Accuracy", value: 81, description: "Correctness of described brand facts." },
  { label: "Sentiment", value: 77, description: "Tone of observed brand descriptions." },
];

export const mockQueries: TrackedQuery[] = [
  {
    id: "q1",
    query: "best project management software for startups",
    category: "Category",
    engine: "ChatGPT",
    mentioned: true,
    recommended: true,
    position: 2,
    trend: "up",
    lastChecked: "2h ago",
    status: "Recommended",
  },
  {
    id: "q2",
    query: "best alternatives to notion",
    category: "Alternatives",
    engine: "Gemini",
    mentioned: true,
    recommended: false,
    position: 6,
    trend: "flat",
    lastChecked: "5h ago",
    status: "Mentioned",
  },
  {
    id: "q3",
    query: "best CRM for small businesses",
    category: "Category",
    engine: "Claude",
    mentioned: false,
    recommended: false,
    position: null,
    trend: "down",
    lastChecked: "1d ago",
    status: "Not Found",
  },
  {
    id: "q4",
    query: "best productivity software",
    category: "Discovery",
    engine: "ChatGPT",
    mentioned: true,
    recommended: true,
    position: 3,
    trend: "up",
    lastChecked: "3h ago",
    status: "Recommended",
  },
  {
    id: "q5",
    query: "affordable team collaboration tools",
    category: "Comparison",
    engine: "Other AI Search",
    mentioned: true,
    recommended: false,
    position: 8,
    trend: "down",
    lastChecked: "1d ago",
    status: "Mentioned",
  },
  {
    id: "q6",
    query: "tools for remote engineering teams",
    category: "Use case",
    engine: "Gemini",
    mentioned: false,
    recommended: false,
    position: null,
    trend: "flat",
    lastChecked: "2d ago",
    status: "Not Found",
  },
];

export const mockCompetitors: Competitor[] = [
  {
    id: "you",
    name: "Your Business",
    score: 72,
    isYou: true,
    sharedQueries: 64,
    wins: 22,
    lostOpportunities: 38,
    reason: "Baseline for comparison across tracked queries.",
  },
  {
    id: "c1",
    name: "Competitor A",
    score: 84,
    sharedQueries: 58,
    wins: 38,
    lostOpportunities: 12,
    reason:
      "Competitor A appears in 38 tracked queries where your business does not, largely through third-party review sources.",
  },
  {
    id: "c2",
    name: "Competitor B",
    score: 78,
    sharedQueries: 47,
    wins: 27,
    lostOpportunities: 19,
    reason:
      "Competitor B is referenced by comparison articles that AI answers frequently summarize.",
  },
  {
    id: "c3",
    name: "Competitor C",
    score: 63,
    sharedQueries: 31,
    wins: 11,
    lostOpportunities: 24,
    reason: "Competitor C wins niche use-case queries with detailed documentation pages.",
  },
];

export const mockCitations: Citation[] = [
  {
    id: "s1",
    source: "g2.com",
    type: "Review platform",
    mentions: 124,
    authority: 92,
    lastSeen: "1d ago",
    impact: "High",
  },
  {
    id: "s2",
    source: "reddit.com",
    type: "Community",
    mentions: 87,
    authority: 78,
    lastSeen: "3h ago",
    impact: "High",
  },
  {
    id: "s3",
    source: "yourdomain.com/docs",
    type: "Owned documentation",
    mentions: 61,
    authority: 64,
    lastSeen: "6h ago",
    impact: "Medium",
  },
  {
    id: "s4",
    source: "techcrunch.com",
    type: "Press",
    mentions: 22,
    authority: 88,
    lastSeen: "2w ago",
    impact: "Medium",
  },
  {
    id: "s5",
    source: "youtube.com",
    type: "Video",
    mentions: 14,
    authority: 71,
    lastSeen: "5d ago",
    impact: "Low",
  },
];

export const mockMissingSources: MissingSource[] = [
  {
    id: "m1",
    source: "Capterra",
    why: "Competitors are cited from Capterra listings in 19 tracked queries.",
    action: "Claim and complete a Capterra profile with structured product details.",
  },
  {
    id: "m2",
    source: "Comparison articles",
    why: "No independent comparison pages reference your product.",
    action: "Publish factual comparison pages and pitch neutral roundups.",
  },
  {
    id: "m3",
    source: "Wikidata / knowledge entities",
    why: "Brand entity data is incomplete, reducing brand accuracy.",
    action: "Add consistent entity data and cross-link official profiles.",
  },
];

export const mockRecommendations: Recommendation[] = [
  {
    id: "r1",
    title: "Improve third-party authority",
    priority: "Critical",
    why: "Competitors are being referenced by more authoritative external sources for tracked queries.",
    impact: "High",
    effort: "Medium",
    steps: [
      "Identify the 10 sources most cited in your tracked queries.",
      "Prioritise review platforms and neutral roundups you are missing.",
      "Provide accurate product data to each source.",
    ],
  },
  {
    id: "r2",
    title: "Strengthen brand entity consistency",
    priority: "Critical",
    why: "Brand descriptions vary across AI engines, reducing observed brand accuracy.",
    impact: "High",
    effort: "Low",
    steps: [
      "Standardise the one-line company description everywhere.",
      "Align category, pricing and audience statements.",
      "Publish an about page with structured data.",
    ],
  },
  {
    id: "r3",
    title: "Create comparison content",
    priority: "High Impact",
    why: "Alternative and comparison queries drive the largest share of observed recommendations.",
    impact: "High",
    effort: "Medium",
    steps: [
      "Build factual comparison pages for the top 5 alternatives.",
      "Include clear feature and pricing tables.",
    ],
  },
  {
    id: "r4",
    title: "Improve product information",
    priority: "High Impact",
    why: "AI answers omit key capabilities that are not stated plainly on your site.",
    impact: "Medium",
    effort: "Low",
    steps: ["Rewrite feature pages in plain, extractable language.", "Add specification blocks."],
  },
  {
    id: "r5",
    title: "Expand citation coverage",
    priority: "Medium Impact",
    why: "Citation coverage is 54%, below the tracked competitor set.",
    impact: "Medium",
    effort: "Medium",
    steps: ["Target the missing sources list.", "Refresh outdated third-party listings."],
  },
  {
    id: "r6",
    title: "Improve FAQ coverage",
    priority: "Medium Impact",
    why: "Question-style queries frequently return competitor documentation instead.",
    impact: "Medium",
    effort: "Low",
    steps: ["Publish concise answers to the top 20 customer questions."],
  },
  {
    id: "r7",
    title: "Add authoritative references",
    priority: "Completed",
    why: "Verified external references were added to core product pages.",
    impact: "Medium",
    effort: "Low",
    steps: ["Completed on the last analysis cycle."],
  },
];

export const mockReports: Report[] = [
  {
    id: "rep1",
    title: "Monthly AI Visibility Report",
    period: "August 2026",
    visibilityChange: 4.2,
    winningQueries: [
      "best project management software for startups",
      "best productivity software",
    ],
    lostQueries: ["best CRM for small businesses", "affordable team collaboration tools"],
    competitorMovement: "Competitor A gained 2.1 points; Competitor C declined 1.4 points.",
    citationChanges: "Citation coverage rose from 51% to 54% across tracked responses.",
    recommendationsCompleted: 3,
  },
  {
    id: "rep2",
    title: "Monthly AI Visibility Report",
    period: "July 2026",
    visibilityChange: 2.8,
    winningQueries: ["best alternatives to notion"],
    lostQueries: ["tools for remote engineering teams"],
    competitorMovement: "Competitor B entered 6 new tracked queries.",
    citationChanges: "Two new review-platform sources observed.",
    recommendationsCompleted: 2,
  },
];
